[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:backend"

[deploy]
startCommand = "npm run start:backend"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production" 