[build]
builder = "nixpacks"

[build.steps]
install = "npm ci --only=production --legacy-peer-deps"
build = "npm run build:backend"
generate = "cd backend && npx prisma generate --schema=../prisma/schema.prisma"

[build.environment]
NPM_CONFIG_PACKAGE_MANAGER = "npm"
NODE_ENV = "production"

[deploy]
startCommand = "npm run start:backend"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production"
NPM_CONFIG_PACKAGE_MANAGER = "npm" 